# SPDX-FileCopyrightText: 2022 Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
default_language_version:
  python: python3.11

repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.8.0
    hooks:
      - id: pyupgrade
        args: [ "--py311-plus" ]

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.10.0
    hooks:
      - id: reorder-python-imports

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: [ "--extend-ignore=B008,W503,E203", "--max-line-length=101" ]


  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.1
    hooks:
      - id: mypy
        args: [ "--ignore-missing-imports", "--config-file=pyproject.toml", "--no-strict-optional" ]
        additional_dependencies:
          - fastapi
          - gql
          - httpx
          - pydantic
          - pytest
          - structlog

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.6
    hooks:
      - id: prettier
        files: \.(js|vue|css|html)$

  - repo: https://github.com/magenta-aps/pre-commit-hooks
    rev: 477acf0d
    hooks:
      - id: auto-ticket-prepare-commit
      - id: auto-ticket-commit

  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.4.0
    hooks:
      - id: check-builtin-literals
      - id: check-byte-order-marker
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: pretty-format-json
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/dosisod/refurb
    rev: v1.17.0
    hooks:
      - id: refurb
