from manager_terminator.autogenerated_graphql_client.get_managers import (
    GetManagersManagers,
)
from manager_terminator.managers import invalid_manager_periods


def test_invalid_manager_periods_no_invalid_periods():
    """Test that a manager with engagement in the same period returns no 'gaps'"""
    manager_info = GetManagersManagers(
        objects=[
            {
                "validities": [
                    {
                        "uuid": "4b27a490-de18-45ad-ae28-01d6de0173a2",
                        "org_unit": [{"uuid": "c4c4ee86-6b32-4bf8-8377-feae8ed94999"}],
                        "person": [
                            {
                                "engagements": [
                                    {
                                        "uuid": "c0247b6d-4248-4509-b5fc-690d65fe047e",
                                        "org_unit": [
                                            {
                                                "uuid": "c4c4ee86-6b32-4bf8-8377-feae8ed94999"
                                            }
                                        ],
                                        "validity": {
                                            "from": "2021-04-01T00:00:00+02:00",
                                            "to": "2024-06-04T00:00:00+02:00",
                                        },
                                    },
                                ]
                            }
                        ],
                        "validity": {
                            "from": "2021-04-01T00:00:00+02:00",
                            "to": "2024-06-04T00:00:00+02:00",
                        },
                    },
                ]
            },
        ]
    )
    periods = invalid_manager_periods(managers=manager_info.objects)
    assert periods == []


def test_invalid_manager_periods_gap_before_manager_start():
    """Test that a manager-role that starts after the engagements period returns no 'gaps'"""
    manager_info = GetManagersManagers(
        objects=[
            {
                "validities": [
                    {
                        "uuid": "8c86dcfb-ac9b-4063-acd7-d34ad095ee11",
                        "org_unit": [{"uuid": "ad1c399f-aff5-4447-8a0c-6e6ad762599a"}],
                        "person": [
                            {
                                "engagements": [
                                    {
                                        "uuid": "48bc0dc9-c675-4aec-acd5-bf35d91e8aca",
                                        "org_unit": [
                                            {
                                                "uuid": "53d49633-a253-4600-a231-3a44a43dccd6"
                                            }
                                        ],
                                        "validity": {
                                            "from": "2020-01-01T00:00:00+01:00",
                                            "to": "2020-12-31T00:00:00+01:00",
                                        },
                                    },
                                    {
                                        "uuid": "cefce5eb-21c5-4d73-b45d-00598a100aa6",
                                        "org_unit": [
                                            {
                                                "uuid": "7564489e-4d05-4029-8b67-21bd71135abd"
                                            }
                                        ],
                                        "validity": {
                                            "from": "2025-07-28T00:00:00+02:00",
                                            "to": None,
                                        },
                                    },
                                ]
                            }
                        ],
                        "validity": {
                            "from": "2021-05-01T00:00:00+02:00",
                            "to": "2023-02-28T00:00:00+01:00",
                        },
                    }
                ]
            },
        ]
    )
    periods = invalid_manager_periods(managers=manager_info.objects)
    assert periods == []
