# SPDX-FileCopyrightText: 2023 Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0

import uuid
from datetime import datetime
from typing import AsyncIterator
from zoneinfo import ZoneInfo

import pytest
from fastapi.applications import FastAPI
from httpx import AsyncClient
from pytest import MonkeyPatch

from manager_terminator.autogenerated_graphql_client import GraphQLClient
from manager_terminator.autogenerated_graphql_client import (
    TestingCreateOrgUnitOrgUnitCreate,
)
from manager_terminator.main import create_app


@pytest.fixture
async def app(monkeypatch: MonkeyPatch) -> FastAPI:
    app = create_app()
    return app


@pytest.fixture
async def graphql_client(mo_client: AsyncClient) -> AsyncIterator[GraphQLClient]:
    graphql_client = GraphQLClient(
        url=f"{mo_client.base_url}/graphql/v22", http_client=mo_client
    )
    async with graphql_client as client:
        yield client


@pytest.fixture
async def default_org_unit(
    graphql_client: GraphQLClient,
) -> TestingCreateOrgUnitOrgUnitCreate:
    tz = ZoneInfo("Europe/Copenhagen")
    long_time_ago = datetime(1970, 1, 1, tzinfo=tz)

    # create an org unit with validity A to infinity
    return await graphql_client._testing__create_org_unit(
        from_date=long_time_ago,
        name="E Corp",
        org_unit_type=uuid.uuid4(),
    )
