# SPDX-FileCopyrightText: 2023 Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0

"""
These are integration tests that exercise the time logic of this integration.
"""

import uuid
from datetime import datetime
from datetime import timedelta
from zoneinfo import ZoneInfo

import pytest
from fastapi import FastAPI
from fastramqpi.pytest_plugin import run_server
from fastramqpi.pytest_util import retry
from more_itertools import one

from manager_terminator.autogenerated_graphql_client import ManagerFilter
from manager_terminator.autogenerated_graphql_client import (
    TestingCreateEmployeeEmployeeCreate,
)
from manager_terminator.autogenerated_graphql_client import (
    TestingCreateOrgUnitOrgUnitCreate,
)
from manager_terminator.depends import GraphQLClient


# TODO(@lorenzo, #68625): re-write this to use the event API directly, as this
#   is not a smoke test.
@pytest.mark.integration_test
async def test_double_engagement(
    app: FastAPI,
    graphql_client: GraphQLClient,
    default_org_unit: TestingCreateOrgUnitOrgUnitCreate,
    default_employee: TestingCreateEmployeeEmployeeCreate,
) -> None:
    """
    Tests the scenario where the same manager has multiple overlapping engagements,
    in this case we expect the manager validity to span the union of the engagements.
    """

    # Arrange
    tz = ZoneInfo("Europe/Copenhagen")
    t1 = datetime(2001, 1, 1, tzinfo=tz)
    t2 = datetime(2002, 1, 1, tzinfo=tz)

    # create engagement A for employee with validity [t1, t2]
    await graphql_client._testing__create_engagement(
        from_date=t1,
        to_date=t2,
        org_unit=default_org_unit.uuid,
        engagement_type=uuid.uuid4(),
        job_function=uuid.uuid4(),
        person=default_employee.uuid,
    )

    # create engagement B for employee with validity [t1, infinity)
    await graphql_client._testing__create_engagement(
        from_date=t1,
        to_date=None,
        org_unit=default_org_unit.uuid,
        engagement_type=uuid.uuid4(),
        job_function=uuid.uuid4(),
        person=default_employee.uuid,
    )

    # create a manager for employee with validity [t1, infinity)
    manager = await graphql_client._testing__create_manager(
        person=default_employee.uuid,
        responsibility=[uuid.uuid4()],
        org_unit=default_org_unit.uuid,
        manager_level=uuid.uuid4(),
        manager_type=uuid.uuid4(),
        from_date=t1,
    )
    manager_uuid = manager.uuid

    # Act - starting the server triggers initialization
    async with run_server(app):
        # Assert
        @retry()
        async def assertions():
            # get manager
            managers = await graphql_client.get_managers(
                filter=ManagerFilter(
                    uuids=[manager_uuid],
                    from_date=None,
                    to_date=None,
                )
            )

            # assert manager has one validity
            manager_obj = one(managers.objects)
            validity = one(manager_obj.validities).validity
            assert validity.from_ == t1
            assert validity.to is None

        await assertions()
