# SPDX-FileCopyrightText: 2023 Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0

"""
These tests exercise the integration's temporal logic.
"""

import uuid
from datetime import datetime
from zoneinfo import ZoneInfo

import pytest
from fastramqpi.pytest_util import retry
from httpx import AsyncClient
from more_itertools import one
from tenacity import stop_after_delay

from manager_terminator.autogenerated_graphql_client import EngagementCreateInput
from manager_terminator.autogenerated_graphql_client import GraphQLClient
from manager_terminator.autogenerated_graphql_client import ManagerCreateInput
from manager_terminator.autogenerated_graphql_client import ManagerFilter
from manager_terminator.autogenerated_graphql_client import ManagerUpdateInput
from manager_terminator.autogenerated_graphql_client import RAValidityInput
from manager_terminator.autogenerated_graphql_client import (
    TestingCreateEmployeeEmployeeCreate,
)
from manager_terminator.autogenerated_graphql_client import (
    TestingCreateOrgUnitOrgUnitCreate,
)


@pytest.mark.integration_test
async def test_half_open_manager(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    default_org_unit: TestingCreateOrgUnitOrgUnitCreate,
    default_employee: TestingCreateEmployeeEmployeeCreate,
):
    """
    Before event (Arrange):

    ```
        time        t1....t2..
        manager     |------ ->
        engagement  |-----|
    ```

    After event (Assert):

    ```
        manager     |-----|
        engagement  |-----|
    ```
    """

    # Arrange

    tz = ZoneInfo("Europe/Copenhagen")
    t1 = datetime(2001, 1, 1, tzinfo=tz)
    t2 = datetime(2002, 1, 1, tzinfo=tz)

    # create an engagement for employee with validity [t1, t2]
    await graphql_client._testing__create_engagement(
        EngagementCreateInput(
            validity=RAValidityInput(from_=t1, to=t2),
            org_unit=default_org_unit.uuid,
            engagement_type=uuid.uuid4(),
            job_function=uuid.uuid4(),
            person=default_employee.uuid,
        )
    )

    # create a manager for employee with validity [t1, infinity)
    manager = await graphql_client._testing__create_manager(
        ManagerCreateInput(
            validity=RAValidityInput(from_=t1),
            person=default_employee.uuid,
            responsibility=[uuid.uuid4()],
            org_unit=default_org_unit.uuid,
            manager_level=uuid.uuid4(),
            manager_type=uuid.uuid4(),
        )
    )
    manager_uuid = manager.uuid

    # Act

    await test_client.post("/events/engagement")

    # Assert

    @retry(stop=stop_after_delay(5))
    async def verify() -> None:
        managers = await graphql_client.get_managers(
            filter=ManagerFilter(
                uuids=[manager_uuid],
                from_date=None,
                to_date=None,
            )
        )
        manager_obj = one(managers.objects)
        manager_validity = one(manager_obj.validities).validity
        assert manager_validity.from_ == t1
        assert manager_validity.to == t2

    await verify()


@pytest.mark.integration_test
async def test_half_open_engagement(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    default_org_unit: TestingCreateOrgUnitOrgUnitCreate,
    default_employee: TestingCreateEmployeeEmployeeCreate,
):
    """
    Before event (Arrange):

    ```
        time        t1....t2....t3
        manager     |-----------|
        engagement        |----- ->
    ```

    After event (Assert):

    ```
        manager           |-----|
        engagement        |----- ->
    ```
    """

    # Arrange

    tz = ZoneInfo("Europe/Copenhagen")
    t1 = datetime(2001, 1, 1, tzinfo=tz)
    t2 = datetime(2002, 1, 1, tzinfo=tz)
    t3 = datetime(2003, 1, 1, tzinfo=tz)

    # create an engagement for employee with validity [t2, infinity)
    await graphql_client._testing__create_engagement(
        EngagementCreateInput(
            validity=RAValidityInput(from_=t2),
            org_unit=default_org_unit.uuid,
            engagement_type=uuid.uuid4(),
            job_function=uuid.uuid4(),
            person=default_employee.uuid,
        )
    )

    # create a manager for employee with validity [t1, t3]
    manager = await graphql_client._testing__create_manager(
        ManagerCreateInput(
            validity=RAValidityInput(from_=t1, to=t3),
            person=default_employee.uuid,
            responsibility=[uuid.uuid4()],
            org_unit=default_org_unit.uuid,
            manager_level=uuid.uuid4(),
            manager_type=uuid.uuid4(),
        )
    )
    manager_uuid = manager.uuid

    # Act

    await test_client.post("/events/engagement")

    # Assert

    @retry(stop=stop_after_delay(5))
    async def verify() -> None:
        managers = await graphql_client.get_managers(
            filter=ManagerFilter(
                uuids=[manager_uuid],
                from_date=None,
                to_date=None,
            )
        )
        manager_obj = one(managers.objects)
        manager_validity = one(manager_obj.validities).validity
        assert manager_validity.from_ == t2
        assert manager_validity.to == t3

    await verify()


@pytest.mark.integration_test
@pytest.mark.envvar({"MANAGER_TERMINATOR__SET_TO_VACANT": "true"})
async def test_idempotent_vacancy(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    default_org_unit: TestingCreateOrgUnitOrgUnitCreate,
    default_employee: TestingCreateEmployeeEmployeeCreate,
) -> None:
    """
    This case verifies that managers that are already vacant are not terminated.

    Before event (Arrange):

    ```
        time         t1....t2....t3....t4.........t5
        manager      |---null----|     |----------|
        engagement1        |-----|
    ```

    After event (Assert):

    ```
        manager      |---null----|     |---null---|
        engagement1        |-----|
    ```

    Note that the second manager validity is put there so that we can await for
    it to be removed, and know that the logic has been triggered.
    """

    # Arrange

    tz = ZoneInfo("Europe/Copenhagen")
    t1 = datetime(2001, 1, 1, tzinfo=tz)
    t2 = datetime(2002, 1, 1, tzinfo=tz)
    t3 = datetime(2003, 1, 1, tzinfo=tz)
    t4 = datetime(2004, 1, 1, tzinfo=tz)
    t5 = datetime(2005, 1, 1, tzinfo=tz)

    # create an engagement for employee with validity [t2, t3]
    await graphql_client._testing__create_engagement(
        EngagementCreateInput(
            validity=RAValidityInput(from_=t2, to=t3),
            org_unit=default_org_unit.uuid,
            engagement_type=uuid.uuid4(),
            job_function=uuid.uuid4(),
            person=default_employee.uuid,
        )
    )

    # create a (vacant) manager with validity [t1, t5], we will poke holes in it later
    manager_uuid = (
        await graphql_client._testing__create_manager(
            ManagerCreateInput(
                validity=RAValidityInput(from_=t1, to=t3),
                person=None,
                responsibility=[uuid.uuid4()],
                org_unit=default_org_unit.uuid,
                manager_level=uuid.uuid4(),
                manager_type=uuid.uuid4(),
            )
        )
    ).uuid

    # terminate manager between [t3, t4]
    await graphql_client.terminate_manager(
        uuid=manager_uuid, terminate_from=t3, terminate_to=t4
    )

    # set manager person between [t4, t5]
    await graphql_client._testing__update_manager(
        ManagerUpdateInput(
            uuid=manager_uuid,
            validity=RAValidityInput(from_=t4, to=t5),
            person=default_employee.uuid,
            responsibility=[uuid.uuid4()],
            org_unit=default_org_unit.uuid,
            manager_level=uuid.uuid4(),
            manager_type=uuid.uuid4(),
        )
    )

    # Act

    await test_client.post("/events/engagement")

    # Assert

    @retry(stop=stop_after_delay(20))
    async def verify() -> None:
        managers = await graphql_client.get_managers(
            filter=ManagerFilter(
                uuids=[manager_uuid],
                from_date=None,
                to_date=None,
            )
        )
        manager_obj = one(managers.objects)

        # The sentinel validity [t4, t5] should be set to vacant, confirming the
        # logic ran. The vacant validity [t1, t3] should remain untouched.
        validities = manager_obj.validities
        validity_1 = validities[0].validity
        person_1 = validities[0].person
        validity_2 = validities[1].validity
        person_2 = validities[1].person
        assert validity_1.from_ == t1
        assert validity_1.to == t3
        assert person_1 is None
        assert validity_2.from_ == t4
        assert validity_2.to == t5
        assert person_2 is None

    await verify()


@pytest.mark.integration_test
async def test_overlap_patterns(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    default_org_unit: TestingCreateOrgUnitOrgUnitCreate,
    default_employee: TestingCreateEmployeeEmployeeCreate,
):
    """
    This case tests different ways engagements and managers can overlap

    Before event (Arrange):
    ```
        time        t1....t2....t3....t4....t5....t6....t7....t8....t9....t10
        manager     |-----------|                 |-----------------------|
        engagement        |-----------|     |-----------|     |-----|
    ```

    After event (Assert):
    ```
        manager           |-----|                 |-----|     |-----|
        engagement        |-----------|     |-----------|     |-----|
    ```
    """

    # Arrange

    tz = ZoneInfo("Europe/Copenhagen")
    t1 = datetime(2001, 1, 1, tzinfo=tz)
    t2 = datetime(2002, 1, 1, tzinfo=tz)
    t3 = datetime(2003, 1, 1, tzinfo=tz)
    t4 = datetime(2004, 1, 1, tzinfo=tz)
    t5 = datetime(2005, 1, 1, tzinfo=tz)
    t6 = datetime(2006, 1, 1, tzinfo=tz)
    t7 = datetime(2007, 1, 1, tzinfo=tz)
    t8 = datetime(2008, 1, 1, tzinfo=tz)
    t9 = datetime(2009, 1, 1, tzinfo=tz)
    t10 = datetime(2010, 1, 1, tzinfo=tz)

    # create three engagements: [t2, t4], [t5, t7], [t8, t9]
    for from_, to in [(t2, t4), (t5, t7), (t8, t9)]:
        await graphql_client._testing__create_engagement(
            EngagementCreateInput(
                validity=RAValidityInput(from_=from_, to=to),
                org_unit=default_org_unit.uuid,
                engagement_type=uuid.uuid4(),
                job_function=uuid.uuid4(),
                person=default_employee.uuid,
            )
        )

    # create manager with validity [t1, t10]. We will poke a hole in its validity next
    manager = await graphql_client._testing__create_manager(
        ManagerCreateInput(
            validity=RAValidityInput(from_=t1, to=t10),
            person=default_employee.uuid,
            responsibility=[uuid.uuid4()],
            org_unit=default_org_unit.uuid,
            manager_level=uuid.uuid4(),
            manager_type=uuid.uuid4(),
        )
    )

    # terminate manager between [t3, t6]
    await graphql_client.terminate_manager(
        uuid=manager.uuid, terminate_from=t3, terminate_to=t6
    )

    # Act

    await test_client.post("/events/engagement")

    # Assert

    @retry(stop=stop_after_delay(20))
    async def verify() -> None:
        managers = await graphql_client.get_managers(
            filter=ManagerFilter(
                uuids=[manager.uuid],
                from_date=None,
                to_date=None,
            )
        )

        # assert manager has three validities [t2, t3], [t6, t7] and [t8, t9]
        manager_obj = one(managers.objects)
        validities = manager_obj.validities
        validity_1 = validities[0].validity
        validity_2 = validities[1].validity
        validity_3 = validities[2].validity
        assert validity_1.from_ == t2
        assert validity_1.to == t3
        assert validity_2.from_ == t6
        assert validity_2.to == t7
        assert validity_3.from_ == t8
        assert validity_3.to == t9
        assert len(validities) == 3

    await verify()


@pytest.mark.integration_test
async def test_overlapping_engagements(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    default_org_unit: TestingCreateOrgUnitOrgUnitCreate,
    default_employee: TestingCreateEmployeeEmployeeCreate,
):
    """
    Multiple overlapping engagements should be handled like one long engagement

    Before event (Arrange):
    ```
        time         t1....t2....t3....t4....t5....t6
        manager      |-----------------------------|
        engagement1        |-----------|
        engagement2              |-----------|
    ```

    After event (Assert):
    ```
        manager            |-----------------|
        engagement1        |-----------|
        engagement2              |-----------|
    ```
    """

    # Arrange

    tz = ZoneInfo("Europe/Copenhagen")
    t1 = datetime(2001, 1, 1, tzinfo=tz)
    t2 = datetime(2002, 1, 1, tzinfo=tz)
    t3 = datetime(2003, 1, 1, tzinfo=tz)
    t4 = datetime(2004, 1, 1, tzinfo=tz)
    t5 = datetime(2005, 1, 1, tzinfo=tz)
    t6 = datetime(2006, 1, 1, tzinfo=tz)

    # create two overlapping engagements: [t2, t4] and [t3, t5]
    for from_, to in [(t2, t4), (t3, t5)]:
        await graphql_client._testing__create_engagement(
            EngagementCreateInput(
                validity=RAValidityInput(from_=from_, to=to),
                org_unit=default_org_unit.uuid,
                engagement_type=uuid.uuid4(),
                job_function=uuid.uuid4(),
                person=default_employee.uuid,
            )
        )

    # create a manager with validity [t1, t6]
    manager = await graphql_client._testing__create_manager(
        ManagerCreateInput(
            validity=RAValidityInput(from_=t1, to=t6),
            person=default_employee.uuid,
            responsibility=[uuid.uuid4()],
            org_unit=default_org_unit.uuid,
            manager_level=uuid.uuid4(),
            manager_type=uuid.uuid4(),
        )
    )

    # Act

    await test_client.post("/events/engagement")

    # Assert

    @retry(stop=stop_after_delay(20))
    async def verify() -> None:
        managers = await graphql_client.get_managers(
            filter=ManagerFilter(
                uuids=[manager.uuid],
                from_date=None,
                to_date=None,
            )
        )

        # assert manager has one validity [t2, t5]
        manager_obj = one(managers.objects)
        manager_validity = one(manager_obj.validities).validity
        assert manager_validity.from_ == t2
        assert manager_validity.to == t5

    await verify()


@pytest.mark.integration_test
async def test_touching_engagements(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    default_org_unit: TestingCreateOrgUnitOrgUnitCreate,
    default_employee: TestingCreateEmployeeEmployeeCreate,
):
    """
    Check that touching engagements don't leave gaps or other strange behavior

    Before event (Arrange):
    ```
        time         t1....t2....t3....t4....t5....t6....t7....t8....t9....t10...t11
        manager            |-----|           |-----------|     |-----------------|
        engagement1  |-----|     |-----|     |-----|           |-----|     |-----|
        engagement2                                |-----|
    ```

    After event (Assert):
    ```
        manager                              |-----------|     |-----|     |-----|
        engagement1  |-----|     |-----|     |-----|           |-----|     |-----|
        engagement2                                |-----|
    ```
    """

    # Arrange

    tz = ZoneInfo("Europe/Copenhagen")
    t1 = datetime(2001, 1, 1, tzinfo=tz)
    t2 = datetime(2002, 1, 1, tzinfo=tz)
    t3 = datetime(2003, 1, 1, tzinfo=tz)
    t4 = datetime(2004, 1, 1, tzinfo=tz)
    t5 = datetime(2005, 1, 1, tzinfo=tz)
    t6 = datetime(2006, 1, 1, tzinfo=tz)
    t7 = datetime(2007, 1, 1, tzinfo=tz)
    t8 = datetime(2008, 1, 1, tzinfo=tz)
    t9 = datetime(2009, 1, 1, tzinfo=tz)
    t10 = datetime(2010, 1, 1, tzinfo=tz)
    t11 = datetime(2011, 1, 1, tzinfo=tz)

    # create engagement1 with 5 separate validities
    for from_, to in [(t1, t2), (t3, t4), (t5, t6), (t8, t9), (t10, t11)]:
        await graphql_client._testing__create_engagement(
            EngagementCreateInput(
                validity=RAValidityInput(from_=from_, to=to),
                org_unit=default_org_unit.uuid,
                engagement_type=uuid.uuid4(),
                job_function=uuid.uuid4(),
                person=default_employee.uuid,
            )
        )

    # create engagement2 with validity [t6, t7], touching the [t5, t6]
    # engagement1 validity
    await graphql_client._testing__create_engagement(
        EngagementCreateInput(
            validity=RAValidityInput(from_=t6, to=t7),
            org_unit=default_org_unit.uuid,
            engagement_type=uuid.uuid4(),
            job_function=uuid.uuid4(),
            person=default_employee.uuid,
        )
    )

    # create a manager with validity [t2, t11]. We will poke holes in it next
    manager = await graphql_client._testing__create_manager(
        ManagerCreateInput(
            validity=RAValidityInput(from_=t2, to=t11),
            person=default_employee.uuid,
            responsibility=[uuid.uuid4()],
            org_unit=default_org_unit.uuid,
            manager_level=uuid.uuid4(),
            manager_type=uuid.uuid4(),
        )
    )

    # terminate manager between [t3, t5]
    await graphql_client.terminate_manager(
        uuid=manager.uuid,
        terminate_from=t3,
        terminate_to=t5,
    )

    # terminate manager between [t7, t8]
    await graphql_client.terminate_manager(
        uuid=manager.uuid,
        terminate_from=t7,
        terminate_to=t8,
    )

    # Act

    await test_client.post("/events/engagement")

    # Assert

    @retry(stop=stop_after_delay(20))
    async def verify() -> None:
        managers = await graphql_client.get_managers(
            filter=ManagerFilter(
                uuids=[manager.uuid],
                from_date=None,
                to_date=None,
            )
        )

        # assert manager has three validities [t5, t7], [t8, t9] and [t10, t11]
        manager_obj = one(managers.objects)
        validities = manager_obj.validities
        validity_1 = validities[0].validity
        validity_2 = validities[1].validity
        validity_3 = validities[2].validity
        assert validity_1.from_ == t5
        assert validity_1.to == t7
        assert validity_2.from_ == t8
        assert validity_2.to == t9
        assert validity_3.from_ == t10
        assert validity_3.to == t11
        assert len(validities) == 3

    await verify()
