# SPDX-FileCopyrightText: 2023 Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0

"""
These tests are minimal reproductions of known bugs that were fixed, to make
sure that we do not accidentally re-introduce them.
"""

import uuid
from datetime import datetime
from datetime import timedelta
from zoneinfo import ZoneInfo

import pytest
from fastapi import FastAPI
from fastramqpi.pytest_plugin import run_server
from fastramqpi.pytest_util import retry
from more_itertools import one

from manager_terminator.autogenerated_graphql_client import GraphQLClient
from manager_terminator.autogenerated_graphql_client import ManagerFilter
from manager_terminator.autogenerated_graphql_client import (
    TestingCreateEmployeeEmployeeCreate,
)
from manager_terminator.autogenerated_graphql_client import (
    TestingCreateOrgUnitOrgUnitCreate,
)


@pytest.mark.integration_test
@pytest.mark.envvar({"MANAGER_TERMINATOR__SET_TO_VACANT": "true"})
async def test_69922_future_termination(
    app: FastAPI,
    graphql_client: GraphQLClient,
    default_org_unit: TestingCreateOrgUnitOrgUnitCreate,
    default_employee: TestingCreateEmployeeEmployeeCreate,
) -> None:
    """
    A termination that sets a future date for the termination should not affect
    the present-day status of managers.

    Before termination (Arrange):
    ```
    ```

    At time t2, a termination is submitted, which takes effect in the future, at
    time t3 (Act).

    After termination (Assert):
    ```
    ```
    """

    # Arrange

    tz = ZoneInfo("Europe/Copenhagen")

    # midnight of today
    t_present = datetime.now(tz).replace(hour=0, minute=0, second=0, microsecond=0)

    t_past = t_present - timedelta(days=365)
    t_future = t_present + timedelta(days=365)

    # create an engagement for employee with validity t_past to infinity
    engagement1 = await graphql_client._testing__create_engagement(
        from_date=t_past,
        org_unit=default_org_unit.uuid,
        engagement_type=uuid.uuid4(),
        job_function=uuid.uuid4(),
        person=default_employee.uuid,
    )
    engagement1_uuid = engagement1.uuid

    engagement2 = await graphql_client._testing__create_engagement(
        from_date=t_past,
        org_unit=default_org_unit.uuid,
        engagement_type=uuid.uuid4(),
        job_function=uuid.uuid4(),
        person=default_employee.uuid,
    )
    engagement2_uuid = engagement2.uuid

    # create a manager for employee with validity t_past to infinity
    manager = await graphql_client._testing__create_manager(
        from_date=t_past,
        person=default_employee.uuid,
        responsibility=[uuid.uuid4()],
        org_unit=default_org_unit.uuid,
        manager_level=uuid.uuid4(),
        manager_type=uuid.uuid4(),
    )
    manager_uuid = manager.uuid

    # Act
    async with run_server(app):
        # terminate the engagement for employee at time t_future, which is in
        # the future compared to the current real time
        await graphql_client._testing__terminate_engagement(engagement1_uuid, t_future)
        await graphql_client._testing__terminate_engagement(engagement2_uuid, t_future)

        # Assert
        @retry()
        async def assertions():
            # get manager
            managers = await graphql_client.get_managers(
                filter=ManagerFilter(
                    uuids=[manager_uuid],
                    from_date=None,
                    to_date=None,
                )
            )
            manager_obj = one(managers.objects)

            # assert manager has two validities [t_past, t_future] and [t_future+1, ...)
            manager_obj = one(managers.objects)
            validities = manager_obj.validities
            validity_1 = validities[0].validity
            validity_2 = validities[1].validity
            assert validity_1.from_ == t_past
            assert validity_1.to == t_future
            assert validity_2.from_ == t_future + timedelta(days=1)
            assert validity_2.to is None
            assert len(validities) == 2

            # assert manager person is set in [t_past, t_future], and null in [t_future+1, ...)
            assert validities[0].person is not None
            person_1 = one(validities[0].person)
            # person_engagement = one(person_1.engagements)
            # assert person_engagement.uuid == engagement1_uuid
            assert validities[1].person is None

        await assertions()
