# SPDX-FileCopyrightText: 2023 Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0

"""
These are smoke tests that only interact with MO through its asynchronous
public APIs. This is a higher standard of correctness but is also takes a long
time to run in pipelines, so we keep them few and simple.
"""

import uuid
from datetime import datetime
from datetime import timedelta
from unittest import skip
from zoneinfo import ZoneInfo

import pytest
from fastapi import FastAPI
from fastramqpi.pytest_plugin import run_server
from fastramqpi.pytest_util import retry
from fastramqpi.pytest_util import stop_after_delay
from more_itertools import one

from manager_terminator.autogenerated_graphql_client import ManagerFilter
from manager_terminator.autogenerated_graphql_client import (
    TestingCreateOrgUnitOrgUnitCreate,
)
from manager_terminator.depends import GraphQLClient


@skip("wip")
@pytest.mark.integration_test
async def test_init_termination_smoke(
    app: FastAPI,
    graphql_client: GraphQLClient,
    default_org_unit: TestingCreateOrgUnitOrgUnitCreate,
) -> None:
    """
    Tests that invalid managers are terminated at initialization time.

    Before initialization (Arrange):

    ```
        time        t1..........t2...

        Engagement  |---valid---|
        Manager     |---valid--- ->
    ```

    Server is started (Act)

    After initialization (Assert):

    ```
        time        t1..........t2...

        Engagement  |---valid---|
        Manager     |---valid---X
    ```

    The manager should appear to be terminated at the same time that the
    engagement is terminated
    """

    # Arrange
    tz = ZoneInfo("Europe/Copenhagen")
    t1 = datetime(2001, 1, 1, tzinfo=tz)
    t2 = datetime(2002, 1, 1, tzinfo=tz)

    # create an employee with infinite validity
    employee = await graphql_client._testing__create_employee(
        given_name="Gneurshk",
        surname="Gronk",
    )
    employee_uuid = employee.uuid

    # create an engagement for employee with validity [t1, t2]
    engagement = await graphql_client._testing__create_engagement(
        from_date=t1,
        to_date=t2,
        org_unit=default_org_unit.uuid,
        engagement_type=uuid.uuid4(),
        job_function=uuid.uuid4(),
        person=employee_uuid,
    )
    engagement_uuid = engagement.uuid

    # create a manager for employee with validity [t1, infinity)
    manager = await graphql_client._testing__create_manager(
        person=employee_uuid,
        responsibility=[uuid.uuid4()],
        org_unit=default_org_unit.uuid,
        manager_level=uuid.uuid4(),
        manager_type=uuid.uuid4(),
        from_date=t1,
    )
    manager_uuid = manager.uuid

    # Act - starting the server triggers initialization
    async with run_server(app):
        # Assert
        @retry(stop=stop_after_delay(5))
        async def assertions():
            # get engagement
            engagements = await graphql_client.get_engagement_objects_by_uuids(
                [engagement_uuid]
            )
            engagement_obj = one(engagements.objects)

            # assert engagement validity is [t1, t2]
            engagement_validity = one(engagement_obj.validities).validity
            assert engagement_validity.from_ == t1
            assert engagement_validity.to == t2

            # get manager
            managers = await graphql_client.get_managers(
                filter=ManagerFilter(
                    uuids=[manager_uuid],
                    from_date=None,
                    to_date=None,
                )
            )
            manager_obj = one(managers.objects)

            # assert manager validity is [t1, t2]
            manager_validity = one(manager_obj.validities).validity
            assert manager_validity.from_ == t1
            assert manager_validity.to == t2

        await assertions()


@skip("wip")
@pytest.mark.integration_test
@pytest.mark.envvar({"MANAGER_TERMINATOR__SET_TO_VACANT": "true"})
async def test_init_set_to_vacant_smoke(
    app: FastAPI,
    graphql_client: GraphQLClient,
    default_org_unit: TestingCreateOrgUnitOrgUnitCreate,
) -> None:
    """
    Tests that invalid managers are set to vacant at initialization time.

    Before initialization (Arrange):

    ```
        time            t1..........t2............

        Engagement      |---valid---|
        Manager         |---valid------------- ->
        Manager.person  |---valid------------- ->
    ```

    Server is started (Act)

    After initialization (Assert):

    ```
        time            t1..........t2............

        Engagement      |---valid---|
        Manager         |---valid-------------- ->
        Manager.person  |---valid---|---null--- ->
    ```

    The manager should appear to be set to vacant, i.e. its "person" should be
    set to `null`, at the same time that the engagement is terminated
    """

    # Arrange
    tz = ZoneInfo("Europe/Copenhagen")
    t1 = datetime(2001, 1, 1, tzinfo=tz)
    t2 = datetime(2002, 1, 1, tzinfo=tz)

    # create an employee with infinite validity
    employee = await graphql_client._testing__create_employee(
        given_name="Gneurshk2",
        surname="Gronk2",
    )
    employee_uuid = employee.uuid

    # create an engagement for employee with validity [t1, t2]
    engagement = await graphql_client._testing__create_engagement(
        from_date=t1,
        to_date=t2,
        org_unit=default_org_unit.uuid,
        engagement_type=uuid.uuid4(),
        job_function=uuid.uuid4(),
        person=employee_uuid,
    )
    engagement_uuid = engagement.uuid

    # create a manager for employee with validity [t1, infinity)
    manager = await graphql_client._testing__create_manager(
        person=employee_uuid,
        responsibility=[uuid.uuid4()],
        org_unit=default_org_unit.uuid,
        manager_level=uuid.uuid4(),
        manager_type=uuid.uuid4(),
        from_date=t1,
    )
    manager_uuid = manager.uuid

    # Act - starting the server triggers initialization
    async with run_server(app):
        # Assert
        @retry(stop=stop_after_delay(10))
        async def assertions():
            # get engagement
            engagements = await graphql_client.get_engagement_objects_by_uuids(
                [engagement_uuid]
            )
            engagement_obj = one(engagements.objects)

            # assert engagement validity is [t1, t2]
            engagement_validity = one(engagement_obj.validities).validity
            assert engagement_validity.from_ == t1
            assert engagement_validity.to == t2

            # get manager
            managers = await graphql_client.get_managers(
                filter=ManagerFilter(
                    uuids=[manager_uuid],
                    from_date=None,
                    to_date=None,
                )
            )

            # assert manager has two validities [t1, t2] and [t2+1, ...)
            manager_obj = one(managers.objects)
            validities = manager_obj.validities
            validity_1 = validities[0].validity
            validity_2 = validities[1].validity
            assert validity_1.from_ == t1
            assert validity_1.to == t2
            assert validity_2.from_ == t2 + timedelta(days=1)
            assert validity_2.to is None
            assert len(validities) == 2

            # assert manager person is set in [t1, t2], and null in [t2+1, ...)
            assert validities[0].person is not None
            person_1 = one(validities[0].person)
            person_engagement = one(person_1.engagements)
            assert person_engagement.uuid == engagement_uuid
            assert validities[1].person is None

        await assertions()
