# SPDX-FileCopyrightText: 2023 Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0

"""
These tests are minimal reproductions of known bugs that were fixed, to make
sure that we do not accidentally re-introduce them.
"""

import uuid
from datetime import datetime
from zoneinfo import ZoneInfo

import pytest
from fastapi import FastAPI
from fastramqpi.pytest_plugin import run_server
from fastramqpi.pytest_util import retry
from fastramqpi.pytest_util import stop_after_delay
from more_itertools import one

from manager_terminator.autogenerated_graphql_client import EngagementCreateInput
from manager_terminator.autogenerated_graphql_client import GraphQLClient
from manager_terminator.autogenerated_graphql_client import ManagerCreateInput
from manager_terminator.autogenerated_graphql_client import ManagerFilter
from manager_terminator.autogenerated_graphql_client import ManagerUpdateInput
from manager_terminator.autogenerated_graphql_client import RAValidityInput
from manager_terminator.autogenerated_graphql_client import (
    TestingCreateEmployeeEmployeeCreate,
)
from manager_terminator.autogenerated_graphql_client import (
    TestingCreateOrgUnitOrgUnitCreate,
)


# NOTE: this test did not actually reproduce the bug, we kept it because it
#   is a pretty complex scenario that exercises the integration well
@pytest.mark.integration_test
@pytest.mark.envvar({"MANAGER_TERMINATOR__SET_TO_VACANT": "true"})
async def test_69922_future_termination(
    app: FastAPI,
    graphql_client: GraphQLClient,
    default_org_unit: TestingCreateOrgUnitOrgUnitCreate,
    default_employee: TestingCreateEmployeeEmployeeCreate,
) -> None:
    """
    This test is a realistic scenario, with multiple adjacent manager validities

    Before termination (Arrange):
    ```
    time            t1............t2.........t3..........t4............t5............t6............t7...
    manager.person  |---valid----------------------------------------------------------------------------------- ->
    manager.level   |---level A--------------------------|---level B---|---level A---|---level B---------------- ->
    engagement      |-------------|          |-----------------------------------------------------|
    ```

    After termination (Assert):
    ```
    manager.person  |---valid-----|---null---|---valid---------------------------------------------|---null----- ->
    manager.level   |---level A--------------------------|---level B---|---level A---|---level B---------------- ->
    engagement      |-------------|          |-----------------------------------------------------|
    ```
    """

    # Arrange
    tz = ZoneInfo("Europe/Copenhagen")
    t1 = datetime(2001, 1, 1, tzinfo=tz)
    t2 = datetime(2002, 1, 1, tzinfo=tz)
    t3 = datetime(2003, 1, 1, tzinfo=tz)
    t4 = datetime(2004, 1, 1, tzinfo=tz)
    t5 = datetime(2005, 1, 1, tzinfo=tz)
    t6 = datetime(2006, 1, 1, tzinfo=tz)
    t7 = datetime(2007, 1, 1, tzinfo=tz)

    level_a = uuid.UUID("aaaaaaaa-0000-4b3d-9b47-9d7dd391b42c")
    level_b = uuid.UUID("bbbbbbbb-0000-4b3d-9b47-9d7dd391b42c")
    manager_type = uuid.uuid4()
    responsibility = [uuid.uuid4()]
    engagement_type = uuid.uuid4()
    job_function = uuid.uuid4()

    # Create engagement 1: [t1, t2]
    await graphql_client._testing__create_engagement(
        EngagementCreateInput(
            validity=RAValidityInput(from_=t1, to=t2),
            org_unit=default_org_unit.uuid,
            engagement_type=engagement_type,
            job_function=job_function,
            person=default_employee.uuid,
        )
    )

    # Create engagement 2: [t3, t7]
    await graphql_client._testing__create_engagement(
        EngagementCreateInput(
            validity=RAValidityInput(from_=t3, to=t7),
            org_unit=default_org_unit.uuid,
            engagement_type=engagement_type,
            job_function=job_function,
            person=default_employee.uuid,
        )
    )

    # Create manager with level A, validity [t1, infinity)
    manager = await graphql_client._testing__create_manager(
        ManagerCreateInput(
            validity=RAValidityInput(from_=t1),
            person=default_employee.uuid,
            responsibility=responsibility,
            org_unit=default_org_unit.uuid,
            manager_level=level_a,
            manager_type=manager_type,
        )
    )
    manager_uuid = manager.uuid

    # Update manager level to B for [t4, infinity)
    await graphql_client._testing__update_manager(
        ManagerUpdateInput(
            uuid=manager_uuid,
            manager_level=level_b,
            person=default_employee.uuid,
            validity=RAValidityInput(from_=t4),
        )
    )

    # Update manager level to A for [t5, t6), "forgetting" to set person
    await graphql_client._testing__update_manager(
        ManagerUpdateInput(
            uuid=manager_uuid,
            manager_level=level_a,
            validity=RAValidityInput(from_=t5, to=t6),
        )
    )

    # Update manager level to A for [t5, t6), realising you forgot to set person
    await graphql_client._testing__update_manager(
        ManagerUpdateInput(
            uuid=manager_uuid,
            manager_level=level_a,
            person=default_employee.uuid,
            validity=RAValidityInput(from_=t5, to=t6),
        )
    )

    # Act - starting the server triggers initialization
    async with run_server(app):
        # Assert
        @retry(stop=stop_after_delay(10))
        async def assertions():
            managers = await graphql_client.get_managers(
                filter=ManagerFilter(
                    uuids=[manager_uuid],
                    from_date=None,
                    to_date=None,
                )
            )

            # assert manager has validities [t1, t2], [t2, t3], [t3, t4], [t4, t5], [t5, t6], [t6, t7], [t7, ...)
            manager_obj = one(managers.objects)
            validities = manager_obj.validities
            validity_1 = validities[0].validity
            validity_2 = validities[1].validity
            validity_3 = validities[2].validity
            validity_4 = validities[3].validity
            validity_5 = validities[4].validity
            validity_6 = validities[5].validity
            validity_7 = validities[6].validity
            assert validity_1.from_ == t1
            assert validity_1.to == t2
            assert validity_2.from_ == t2
            assert validity_2.to == t3
            assert validity_3.from_ == t3
            assert validity_3.to == t4
            assert validity_4.from_ == t4
            assert validity_4.to == t5
            assert validity_5.from_ == t5
            assert validity_5.to == t6
            assert validity_6.from_ == t6
            assert validity_6.to == t7
            assert validity_7.from_ == t7
            assert validity_7.to is None
            assert len(validities) == 7

            # assert manager has person in [t1, t2] and [t3, t7]; and null in [t2, t3], [t7, ...)
            person_1 = validities[0].person_response
            person_2 = validities[1].person_response
            person_3 = validities[2].person_response
            person_4 = validities[3].person_response
            person_5 = validities[4].person_response
            person_6 = validities[5].person_response
            person_7 = validities[6].person_response
            assert person_1 is not None
            assert person_2 is None
            assert person_3 is not None
            assert person_4 is not None
            assert person_5 is not None
            assert person_6 is not None
            assert person_7 is None

        await assertions()
