# SPDX-FileCopyrightText: 2023 Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0

"""
These are integration tests that exercise the time logic of this integration.
"""

import uuid
from datetime import datetime
from zoneinfo import ZoneInfo

import pytest
from fastapi import FastAPI

from manager_terminator.autogenerated_graphql_client import (
    TestingCreateOrgUnitOrgUnitCreate,
)
from manager_terminator.depends import GraphQLClient


# TODO(@lorenzo, #68625): re-write this to use the event API directly, as this
#   is not a smoke test.
@pytest.mark.integration
async def test_double_engagement(
    app: FastAPI,
    graphql_client: GraphQLClient,
    default_org_unit: TestingCreateOrgUnitOrgUnitCreate,
) -> None:
    """
    Tests the scenario where the same manager has multiple overlapping engagements,
    in this case we expect the manager validity to span the union of the engagements.
    """

    # Arrange
    tz = ZoneInfo("Europe/Copenhagen")
    t1 = datetime(2001, 1, 1, tzinfo=tz)
    t2 = datetime(2002, 1, 1, tzinfo=tz)

    # create an employee with infinite validity
    employee = await graphql_client._testing__create_employee(
        given_name="Gneurshk",
        surname="Gronk",
    )
    employee_uuid = employee.uuid

    # create engagement A for employee with validity [t1, t2]
    engagement_a = await graphql_client._testing__create_engagement(
        from_date=t1,
        to_date=t2,
        org_unit=default_org_unit.uuid,
        engagement_type=uuid.uuid4(),
        job_function=uuid.uuid4(),
        person=employee_uuid,
    )
    engagement_a_uuid = engagement_a.uuid

    # create engagement B for employee with validity [t1, infinity)
    engagement_b = await graphql_client._testing__create_engagement(
        from_date=t1,
        to_date=t2,
        org_unit=default_org_unit.uuid,
        engagement_type=uuid.uuid4(),
        job_function=uuid.uuid4(),
        person=employee_uuid,
    )
    engagement_b_uuid = engagement_b.uuid

    # create a manager for employee with validity [t1, infinity)
    manager = await graphql_client._testing__create_manager(
        person=employee_uuid,
        responsibility=[uuid.uuid4()],
        org_unit=default_org_unit.uuid,
        manager_level=uuid.uuid4(),
        manager_type=uuid.uuid4(),
        from_date=t1,
    )
    manager_uuid = manager.uuid
