# SPDX-FileCopyrightText: 2023 Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0

"""
These tests are minimal reproductions of known bugs that were fixed, to make
sure that we do not accidentally re-introduce them.
"""

import asyncio
import uuid
from datetime import datetime
from zoneinfo import ZoneInfo

import pytest
from fastapi import FastAPI
from fastramqpi.pytest_plugin import run_server
from fastramqpi.pytest_util import retry
from fastramqpi.pytest_util import stop_after_delay
from more_itertools import one

from manager_terminator.autogenerated_graphql_client import GraphQLClient
from manager_terminator.autogenerated_graphql_client import ManagerFilter
from manager_terminator.autogenerated_graphql_client import ManagerUpdateInput
from manager_terminator.autogenerated_graphql_client import RAValidityInput
from manager_terminator.autogenerated_graphql_client import (
    TestingCreateEmployeeEmployeeCreate,
)
from manager_terminator.autogenerated_graphql_client import (
    TestingCreateOrgUnitOrgUnitCreate,
)


@pytest.mark.integration_test
@pytest.mark.envvar({"MANAGER_TERMINATOR__SET_TO_VACANT": "true"})
async def test_69922_future_termination(
    app: FastAPI,
    graphql_client: GraphQLClient,
    default_org_unit: TestingCreateOrgUnitOrgUnitCreate,
    default_employee: TestingCreateEmployeeEmployeeCreate,
) -> None:
    """
    Before termination (Arrange):
    ```
    time            t1............t2.........t3..........t4............t5............t6............t7...
    manager.person  |---valid----------------------------------------------------------------------------------- ->
    manager.level   |---level A--------------------------|---level B---|---level A---|---level B---------------- ->
    engagement      |-------------|          |-----------------------------------------------------|
    ```

    After termination (Assert):
    ```
    manager.person  |---valid-----|---null---|---valid---------------------------------------------|---null----- ->
    manager.level   |---level A--------------------------|---level B---|---level A---|---level B---------------- ->
    engagement      |-------------|          |-----------------------------------------------------|
    ```
    """

    # Arrange
    tz = ZoneInfo("Europe/Copenhagen")
    t1 = datetime(2001, 1, 1, tzinfo=tz)
    t2 = datetime(2002, 1, 1, tzinfo=tz)
    t3 = datetime(2003, 1, 1, tzinfo=tz)
    t4 = datetime(2004, 1, 1, tzinfo=tz)
    t5 = datetime(2005, 1, 1, tzinfo=tz)
    t6 = datetime(2006, 1, 1, tzinfo=tz)
    t7 = datetime(2007, 1, 1, tzinfo=tz)

    level_a = uuid.UUID("aaaaaaaa-0000-4b3d-9b47-9d7dd391b42c")
    level_b = uuid.UUID("bbbbbbbb-0000-4b3d-9b47-9d7dd391b42c")
    manager_type = uuid.uuid4()
    responsibility = [uuid.uuid4()]
    engagement_type = uuid.uuid4()
    job_function = uuid.uuid4()

    # Create engagement 1: [t1, t2]
    await graphql_client._testing__create_engagement(
        from_date=t1,
        to_date=t2,
        org_unit=default_org_unit.uuid,
        engagement_type=engagement_type,
        job_function=job_function,
        person=default_employee.uuid,
    )

    # Create engagement 2: [t3, t7]
    await graphql_client._testing__create_engagement(
        from_date=t3,
        to_date=t7,
        org_unit=default_org_unit.uuid,
        engagement_type=engagement_type,
        job_function=job_function,
        person=default_employee.uuid,
    )

    # Create manager with level A, validity [t1, infinity)
    manager = await graphql_client._testing__create_manager(
        person=default_employee.uuid,
        responsibility=responsibility,
        org_unit=default_org_unit.uuid,
        manager_level=level_a,
        manager_type=manager_type,
        from_date=t1,
    )
    manager_uuid = manager.uuid

    # Update manager level to B for [t4, infinity)
    await graphql_client._testing__update_manager(
        ManagerUpdateInput(
            uuid=manager_uuid,
            manager_level=level_b,
            person=default_employee.uuid,
            validity=RAValidityInput(from_=t4),
        )
    )

    # Update manager level to A for [t5, t6), "forgetting" to set person
    await graphql_client._testing__update_manager(
        ManagerUpdateInput(
            uuid=manager_uuid,
            manager_level=level_a,
            validity=RAValidityInput(from_=t5, to=t6),
        )
    )

    # Update manager level to A for [t5, t6), realising you forgot to set person
    await graphql_client._testing__update_manager(
        ManagerUpdateInput(
            uuid=manager_uuid,
            manager_level=level_a,
            person=default_employee.uuid,
            validity=RAValidityInput(from_=t5, to=t6),
        )
    )

    # Act - starting the server triggers initialization
    async with run_server(app):
        await asyncio.sleep(99999)

        # Assert
        @retry(stop=stop_after_delay(10))
        async def assertions():
            managers = await graphql_client.get_managers(
                filter=ManagerFilter(
                    uuids=[manager_uuid],
                    from_date=None,
                    to_date=None,
                )
            )
            manager_obj = one(managers.objects)
            validities = sorted(manager_obj.validities, key=lambda v: v.validity.from_)

            # The manager should have been split into periods where person is
            # set vs null, according to engagement coverage:
            #   [t1, t2]: person set (covered by engagement 1)
            #   (t2, t3): person null (gap between engagements)
            #   [t3, t6]: person set (covered by engagement 2)
            #   (t6, ...): person null (after last engagement)

            person_timeline = [
                (
                    v.validity.from_,
                    v.validity.to,
                    v.person is not None and len(v.person) > 0,
                )
                for v in validities
            ]

            for from_, to, has_person in person_timeline:
                if to is not None and to <= t2:
                    # Period within first engagement coverage
                    assert has_person, f"Expected person to be set in [{from_}, {to}]"
                elif from_ > t2 and (to is not None and to < t3):
                    # Gap between engagements
                    assert not has_person, (
                        f"Expected person to be null in [{from_}, {to}]"
                    )
                elif from_ >= t3 and (to is not None and to <= t6):
                    # Period within second engagement coverage
                    assert has_person, f"Expected person to be set in [{from_}, {to}]"
                elif from_ > t6:
                    # After last engagement
                    assert not has_person, (
                        f"Expected person to be null in [{from_}, {to}]"
                    )

            # Verify we have both vacant and non-vacant periods
            assert any(not hp for _, _, hp in person_timeline), (
                "Expected at least one vacant period"
            )
            assert any(hp for _, _, hp in person_timeline), (
                "Expected at least one non-vacant period"
            )

        await assertions()
