# Generated by ariadne-codegen on 2023-08-28 15:14
# Source: queries.graphql

from datetime import datetime
from uuid import UUID

from .async_base_client import AsyncBaseClient
from .get_engagement_objects import (
    GetEngagementObjects,
    GetEngagementObjectsEngagements,
)
from .get_managers import GetManagers, GetManagersManagers
from .terminate_manager import TerminateManager, TerminateManagerManagerTerminate


def gql(q: str) -> str:
    return q


class GraphQLClient(AsyncBaseClient):
    async def get_managers(self) -> GetManagersManagers:
        query = gql(
            """
            query GetManagers {
              managers(from_date: null, to_date: null) {
                objects {
                  objects {
                    uuid
                    org_unit {
                      uuid
                    }
                    employee {
                      engagements {
                        uuid
                        org_unit {
                          uuid
                        }
                        validity {
                          from
                          to
                        }
                      }
                    }
                    validity {
                      from
                      to
                    }
                  }
                }
              }
            }
            """
        )
        variables: dict[str, object] = {}
        response = await self.execute(query=query, variables=variables)
        data = self.get_data(response)
        return GetManagers.parse_obj(data).managers

    async def terminate_manager(
        self, termination_date: datetime, uuid: UUID
    ) -> TerminateManagerManagerTerminate:
        query = gql(
            """
            mutation TerminateManager($termination_date: DateTime!, $uuid: UUID!) {
              manager_terminate(input: {to: $termination_date, uuid: $uuid}) {
                uuid
              }
            }
            """
        )
        variables: dict[str, object] = {
            "termination_date": termination_date,
            "uuid": uuid,
        }
        response = await self.execute(query=query, variables=variables)
        data = self.get_data(response)
        return TerminateManager.parse_obj(data).manager_terminate

    async def get_engagement_objects(
        self, engagement_uuid: UUID
    ) -> GetEngagementObjectsEngagements:
        query = gql(
            """
            query GetEngagementObjects($engagement_uuid: UUID!) {
              engagements(uuids: [$engagement_uuid]) {
                objects {
                  objects {
                    org_unit {
                      uuid
                      name
                    }
                    validity {
                      from
                      to
                    }
                    employee {
                      uuid
                      engagements {
                        uuid
                        org_unit {
                          uuid
                        }
                        validity {
                          from
                          to
                        }
                      }
                      manager_roles {
                        uuid
                        org_unit {
                          uuid
                        }
                        validity {
                          from
                          to
                        }
                      }
                    }
                  }
                }
              }
            }
            """
        )
        variables: dict[str, object] = {"engagement_uuid": engagement_uuid}
        response = await self.execute(query=query, variables=variables)
        data = self.get_data(response)
        return GetEngagementObjects.parse_obj(data).engagements
