# Generated by ariadne-codegen on 2023-10-31 13:27
# Source: queries.graphql

from datetime import datetime
from typing import List, Optional
from uuid import UUID

from pydantic import Field

from .base_model import BaseModel


class GetEngagementObjectsByUuids(BaseModel):
    engagements: "GetEngagementObjectsByUuidsEngagements"


class GetEngagementObjectsByUuidsEngagements(BaseModel):
    objects: List["GetEngagementObjectsByUuidsEngagementsObjects"]


class GetEngagementObjectsByUuidsEngagementsObjects(BaseModel):
    objects: List["GetEngagementObjectsByUuidsEngagementsObjectsObjects"]


class GetEngagementObjectsByUuidsEngagementsObjectsObjects(BaseModel):
    uuid: UUID
    org_unit: List["GetEngagementObjectsByUuidsEngagementsObjectsObjectsOrgUnit"]
    person: List["GetEngagementObjectsByUuidsEngagementsObjectsObjectsPerson"]
    validity: "GetEngagementObjectsByUuidsEngagementsObjectsObjectsValidity"


class GetEngagementObjectsByUuidsEngagementsObjectsObjectsOrgUnit(BaseModel):
    uuid: UUID


class GetEngagementObjectsByUuidsEngagementsObjectsObjectsPerson(BaseModel):
    uuid: UUID


class GetEngagementObjectsByUuidsEngagementsObjectsObjectsValidity(BaseModel):
    from_: datetime = Field(alias="from")
    to: Optional[datetime]


GetEngagementObjectsByUuids.update_forward_refs()
GetEngagementObjectsByUuidsEngagements.update_forward_refs()
GetEngagementObjectsByUuidsEngagementsObjects.update_forward_refs()
GetEngagementObjectsByUuidsEngagementsObjectsObjects.update_forward_refs()
GetEngagementObjectsByUuidsEngagementsObjectsObjectsOrgUnit.update_forward_refs()
GetEngagementObjectsByUuidsEngagementsObjectsObjectsPerson.update_forward_refs()
GetEngagementObjectsByUuidsEngagementsObjectsObjectsValidity.update_forward_refs()
