# Generated by ariadne-codegen on 2023-10-31 10:04
# Source: queries.graphql

from datetime import datetime
from typing import List, Optional
from uuid import UUID

from pydantic import Field

from .base_model import BaseModel


class GetEngagementObjectsByUuid(BaseModel):
    engagements: "GetEngagementObjectsByUuidEngagements"


class GetEngagementObjectsByUuidEngagements(BaseModel):
    objects: List["GetEngagementObjectsByUuidEngagementsObjects"]


class GetEngagementObjectsByUuidEngagementsObjects(BaseModel):
    validities: List["GetEngagementObjectsByUuidEngagementsObjectsValidities"]


class GetEngagementObjectsByUuidEngagementsObjectsValidities(BaseModel):
    uuid: UUID
    org_unit: List["GetEngagementObjectsByUuidEngagementsObjectsValiditiesOrgUnit"]
    person: List["GetEngagementObjectsByUuidEngagementsObjectsValiditiesPerson"]
    validity: "GetEngagementObjectsByUuidEngagementsObjectsValiditiesValidity"


class GetEngagementObjectsByUuidEngagementsObjectsValiditiesOrgUnit(BaseModel):
    uuid: UUID


class GetEngagementObjectsByUuidEngagementsObjectsValiditiesPerson(BaseModel):
    uuid: UUID


class GetEngagementObjectsByUuidEngagementsObjectsValiditiesValidity(BaseModel):
    from_: datetime = Field(alias="from")
    to: Optional[datetime]


GetEngagementObjectsByUuid.update_forward_refs()
GetEngagementObjectsByUuidEngagements.update_forward_refs()
GetEngagementObjectsByUuidEngagementsObjects.update_forward_refs()
GetEngagementObjectsByUuidEngagementsObjectsValidities.update_forward_refs()
GetEngagementObjectsByUuidEngagementsObjectsValiditiesOrgUnit.update_forward_refs()
GetEngagementObjectsByUuidEngagementsObjectsValiditiesPerson.update_forward_refs()
GetEngagementObjectsByUuidEngagementsObjectsValiditiesValidity.update_forward_refs()
