# Generated by ariadne-codegen on 2025-02-05 10:52
# Source: queries.graphql

from datetime import datetime
from typing import List, Optional
from uuid import UUID

from pydantic import Field

from .base_model import BaseModel


class GetEmployeeManagers(BaseModel):
    managers: "GetEmployeeManagersManagers"


class GetEmployeeManagersManagers(BaseModel):
    objects: List["GetEmployeeManagersManagersObjects"]


class GetEmployeeManagersManagersObjects(BaseModel):
    validities: List["GetEmployeeManagersManagersObjectsValidities"]


class GetEmployeeManagersManagersObjectsValidities(BaseModel):
    uuid: UUID
    org_unit: List["GetEmployeeManagersManagersObjectsValiditiesOrgUnit"]
    person: Optional[List["GetEmployeeManagersManagersObjectsValiditiesPerson"]]
    validity: "GetEmployeeManagersManagersObjectsValiditiesValidity"


class GetEmployeeManagersManagersObjectsValiditiesOrgUnit(BaseModel):
    uuid: UUID


class GetEmployeeManagersManagersObjectsValiditiesPerson(BaseModel):
    engagements: List["GetEmployeeManagersManagersObjectsValiditiesPersonEngagements"]


class GetEmployeeManagersManagersObjectsValiditiesPersonEngagements(BaseModel):
    uuid: UUID
    org_unit: List[
        "GetEmployeeManagersManagersObjectsValiditiesPersonEngagementsOrgUnit"
    ]
    validity: "GetEmployeeManagersManagersObjectsValiditiesPersonEngagementsValidity"


class GetEmployeeManagersManagersObjectsValiditiesPersonEngagementsOrgUnit(BaseModel):
    uuid: UUID


class GetEmployeeManagersManagersObjectsValiditiesPersonEngagementsValidity(BaseModel):
    from_: datetime = Field(alias="from")
    to: Optional[datetime]


class GetEmployeeManagersManagersObjectsValiditiesValidity(BaseModel):
    from_: datetime = Field(alias="from")
    to: Optional[datetime]


GetEmployeeManagers.update_forward_refs()
GetEmployeeManagersManagers.update_forward_refs()
GetEmployeeManagersManagersObjects.update_forward_refs()
GetEmployeeManagersManagersObjectsValidities.update_forward_refs()
GetEmployeeManagersManagersObjectsValiditiesOrgUnit.update_forward_refs()
GetEmployeeManagersManagersObjectsValiditiesPerson.update_forward_refs()
GetEmployeeManagersManagersObjectsValiditiesPersonEngagements.update_forward_refs()
GetEmployeeManagersManagersObjectsValiditiesPersonEngagementsOrgUnit.update_forward_refs()
GetEmployeeManagersManagersObjectsValiditiesPersonEngagementsValidity.update_forward_refs()
GetEmployeeManagersManagersObjectsValiditiesValidity.update_forward_refs()
