# Generated by ariadne-codegen on 2023-10-31 13:27
# Source: queries.graphql

from datetime import datetime
from typing import List, Optional
from uuid import UUID

from pydantic import Field

from .base_model import BaseModel


class GetManagers(BaseModel):
    managers: "GetManagersManagers"


class GetManagersManagers(BaseModel):
    objects: List["GetManagersManagersObjects"]


class GetManagersManagersObjects(BaseModel):
    objects: List["GetManagersManagersObjectsObjects"]


class GetManagersManagersObjectsObjects(BaseModel):
    uuid: UUID
    org_unit: List["GetManagersManagersObjectsObjectsOrgUnit"]
    person: Optional[List["GetManagersManagersObjectsObjectsPerson"]]
    validity: "GetManagersManagersObjectsObjectsValidity"


class GetManagersManagersObjectsObjectsOrgUnit(BaseModel):
    uuid: UUID


class GetManagersManagersObjectsObjectsPerson(BaseModel):
    engagements: List["GetManagersManagersObjectsObjectsPersonEngagements"]


class GetManagersManagersObjectsObjectsPersonEngagements(BaseModel):
    uuid: UUID
    org_unit: List["GetManagersManagersObjectsObjectsPersonEngagementsOrgUnit"]
    validity: "GetManagersManagersObjectsObjectsPersonEngagementsValidity"


class GetManagersManagersObjectsObjectsPersonEngagementsOrgUnit(BaseModel):
    uuid: UUID


class GetManagersManagersObjectsObjectsPersonEngagementsValidity(BaseModel):
    from_: datetime = Field(alias="from")
    to: Optional[datetime]


class GetManagersManagersObjectsObjectsValidity(BaseModel):
    from_: datetime = Field(alias="from")
    to: Optional[datetime]


GetManagers.update_forward_refs()
GetManagersManagers.update_forward_refs()
GetManagersManagersObjects.update_forward_refs()
GetManagersManagersObjectsObjects.update_forward_refs()
GetManagersManagersObjectsObjectsOrgUnit.update_forward_refs()
GetManagersManagersObjectsObjectsPerson.update_forward_refs()
GetManagersManagersObjectsObjectsPersonEngagements.update_forward_refs()
GetManagersManagersObjectsObjectsPersonEngagementsOrgUnit.update_forward_refs()
GetManagersManagersObjectsObjectsPersonEngagementsValidity.update_forward_refs()
GetManagersManagersObjectsObjectsValidity.update_forward_refs()
