# Generated by ariadne-codegen on 2025-01-29 23:35
# Source: queries.graphql

from datetime import datetime
from typing import List, Optional
from uuid import UUID

from pydantic import Field

from .base_model import BaseModel


class GetManagers(BaseModel):
    managers: "GetManagersManagers"


class GetManagersManagers(BaseModel):
    objects: List["GetManagersManagersObjects"]


class GetManagersManagersObjects(BaseModel):
    validities: List["GetManagersManagersObjectsValidities"]


class GetManagersManagersObjectsValidities(BaseModel):
    uuid: UUID
    org_unit: List["GetManagersManagersObjectsValiditiesOrgUnit"]
    person: Optional[List["GetManagersManagersObjectsValiditiesPerson"]]
    validity: "GetManagersManagersObjectsValiditiesValidity"


class GetManagersManagersObjectsValiditiesOrgUnit(BaseModel):
    uuid: UUID


class GetManagersManagersObjectsValiditiesPerson(BaseModel):
    engagements: List["GetManagersManagersObjectsValiditiesPersonEngagements"]


class GetManagersManagersObjectsValiditiesPersonEngagements(BaseModel):
    uuid: UUID
    org_unit: List["GetManagersManagersObjectsValiditiesPersonEngagementsOrgUnit"]
    validity: "GetManagersManagersObjectsValiditiesPersonEngagementsValidity"


class GetManagersManagersObjectsValiditiesPersonEngagementsOrgUnit(BaseModel):
    uuid: UUID


class GetManagersManagersObjectsValiditiesPersonEngagementsValidity(BaseModel):
    from_: datetime = Field(alias="from")
    to: Optional[datetime]


class GetManagersManagersObjectsValiditiesValidity(BaseModel):
    from_: datetime = Field(alias="from")
    to: Optional[datetime]


GetManagers.update_forward_refs()
GetManagersManagers.update_forward_refs()
GetManagersManagersObjects.update_forward_refs()
GetManagersManagersObjectsValidities.update_forward_refs()
GetManagersManagersObjectsValiditiesOrgUnit.update_forward_refs()
GetManagersManagersObjectsValiditiesPerson.update_forward_refs()
GetManagersManagersObjectsValiditiesPersonEngagements.update_forward_refs()
GetManagersManagersObjectsValiditiesPersonEngagementsOrgUnit.update_forward_refs()
GetManagersManagersObjectsValiditiesPersonEngagementsValidity.update_forward_refs()
GetManagersManagersObjectsValiditiesValidity.update_forward_refs()
