# Generated by ariadne-codegen on 2023-10-30 15:47
# Source: queries.graphql

from datetime import datetime
from typing import List, Optional
from uuid import UUID

from pydantic import Field

from .base_model import BaseModel


class GetEngagementObjectsByUUID(BaseModel):
    engagements: "GetEngagementObjectsByUUIDEngagements"


class GetEngagementObjectsByUUIDEngagements(BaseModel):
    objects: List["GetEngagementObjectsByUUIDEngagementsObjects"]


class GetEngagementObjectsByUUIDEngagementsObjects(BaseModel):
    objects: List["GetEngagementObjectsByUUIDEngagementsObjectsObjects"]


class GetEngagementObjectsByUUIDEngagementsObjectsObjects(BaseModel):
    uuid: UUID
    org_unit: List["GetEngagementObjectsByUUIDEngagementsObjectsObjectsOrgUnit"]
    person: List["GetEngagementObjectsByUUIDEngagementsObjectsObjectsPerson"]
    validity: "GetEngagementObjectsByUUIDEngagementsObjectsObjectsValidity"


class GetEngagementObjectsByUUIDEngagementsObjectsObjectsOrgUnit(BaseModel):
    uuid: UUID


class GetEngagementObjectsByUUIDEngagementsObjectsObjectsPerson(BaseModel):
    uuid: UUID


class GetEngagementObjectsByUUIDEngagementsObjectsObjectsValidity(BaseModel):
    from_: datetime = Field(alias="from")
    to: Optional[datetime]


GetEngagementObjectsByUUID.update_forward_refs()
GetEngagementObjectsByUUIDEngagements.update_forward_refs()
GetEngagementObjectsByUUIDEngagementsObjects.update_forward_refs()
GetEngagementObjectsByUUIDEngagementsObjectsObjects.update_forward_refs()
GetEngagementObjectsByUUIDEngagementsObjectsObjectsOrgUnit.update_forward_refs()
GetEngagementObjectsByUUIDEngagementsObjectsObjectsPerson.update_forward_refs()
GetEngagementObjectsByUUIDEngagementsObjectsObjectsValidity.update_forward_refs()
