# Generated by ariadne-codegen on 2023-10-30 15:47
# Source: queries.graphql

from datetime import datetime
from typing import List, Optional
from uuid import UUID

from pydantic import Field

from .base_model import BaseModel


class GetEngagementObjectsByUUID(BaseModel):
    engagements: "GetEngagementObjectsByUUIDEngagements"


class GetEngagementObjectsByUUIDEngagements(BaseModel):
    objects: List["GetEngagementObjectsByUUIDEngagementsObjects"]


class GetEngagementObjectsByUUIDEngagementsObjects(BaseModel):
    validities: List["GetEngagementObjectsByUUIDEngagementsObjectsValidities"]


class GetEngagementObjectsByUUIDEngagementsObjectsValidities(BaseModel):
    uuid: UUID
    org_unit: List["GetEngagementObjectsByUUIDEngagementsObjectsValiditiesOrgUnit"]
    person: List["GetEngagementObjectsByUUIDEngagementsObjectsValiditiesPerson"]
    validity: "GetEngagementObjectsByUUIDEngagementsObjectsValiditiesValidity"


class GetEngagementObjectsByUUIDEngagementsObjectsValiditiesOrgUnit(BaseModel):
    uuid: UUID


class GetEngagementObjectsByUUIDEngagementsObjectsValiditiesPerson(BaseModel):
    uuid: UUID


class GetEngagementObjectsByUUIDEngagementsObjectsValiditiesValidity(BaseModel):
    from_: datetime = Field(alias="from")
    to: Optional[datetime]


GetEngagementObjectsByUUID.update_forward_refs()
GetEngagementObjectsByUUIDEngagements.update_forward_refs()
GetEngagementObjectsByUUIDEngagementsObjects.update_forward_refs()
GetEngagementObjectsByUUIDEngagementsObjectsValidities.update_forward_refs()
GetEngagementObjectsByUUIDEngagementsObjectsValiditiesOrgUnit.update_forward_refs()
GetEngagementObjectsByUUIDEngagementsObjectsValiditiesPerson.update_forward_refs()
GetEngagementObjectsByUUIDEngagementsObjectsValiditiesValidity.update_forward_refs()
