# Generated by ariadne-codegen on 2025-01-31 13:36
# Source: queries.graphql

from uuid import UUID

from .base_model import BaseModel


class UpdateManager(BaseModel):
    manager_terminate: "UpdateManagerManagerTerminate"


class UpdateManagerManagerTerminate(BaseModel):
    uuid: UUID


UpdateManager.update_forward_refs()
UpdateManagerManagerTerminate.update_forward_refs()
