# SPDX-FileCopyrightText: 2023 Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
import json

import structlog
from fastapi import APIRouter
from fastapi.encoders import jsonable_encoder

from manager_terminator.autogenerated_graphql_client import ManagerFilter
from manager_terminator.depends import GraphQLClient
from manager_terminator.depends import Settings

router = APIRouter()
logger = structlog.stdlib.get_logger()


@router.post("/trigger/all")
async def _trigger_all(settings: Settings, gql_client: GraphQLClient, limit=500):
    logger.info("Received trigger all request")

    me = await gql_client.get_actor()
    logger.debug("Found out who I am", me=json.dumps(jsonable_encoder(me)))

    next_cursor = None
    managers_refreshed = 0
    while True:
        batch = await gql_client.refresh_manager(
            owner=me.actor.uuid,
            filter=ManagerFilter(from_date=None, to_date=None),
            cursor=next_cursor,
            limit=limit,
        )
        next_cursor = batch.page_info.next_cursor
        managers_refreshed += len(batch.objects)
        if next_cursor is None:
            break

    logger.info(f"Refreshed {managers_refreshed} managers")
