# SPDX-FileCopyrightText: 2023 Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0

import structlog
from fastapi import FastAPI
from fastramqpi.events import GraphQLEvents
from fastramqpi.events import Listener
from fastramqpi.main import FastRAMQPI

from manager_terminator.autogenerated_graphql_client import GraphQLClient

from .depends import Settings
from .events import events_router

logger = structlog.get_logger(__name__)


def create_app() -> FastAPI:
    settings = Settings()
    fastramqpi = FastRAMQPI(
        application_name="os2mo-manager-terminator",
        settings=settings.fastramqpi,
        graphql_version=29,
        graphql_client_cls=GraphQLClient,
        graphql_events=GraphQLEvents(
            declare_listeners=[
                Listener(
                    namespace="mo",
                    user_key="engagement",
                    routing_key="engagement",
                    path="/events/engagement",
                )
            ]
        ),
    )

    fastramqpi.add_context(settings=settings)

    app = fastramqpi.get_app()
    app.include_router(events_router)

    return app
