# SPDX-FileCopyrightText: 2023 Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
import json

import structlog
from fastapi import APIRouter
from fastapi import FastAPI
from fastapi.encoders import jsonable_encoder
from fastramqpi.events import GraphQLEvents
from fastramqpi.events import Listener
from fastramqpi.main import FastRAMQPI
from fastramqpi.ramqp.mo import MORouter
from starlette.status import HTTP_200_OK

import manager_terminator.managers as managers
from manager_terminator import depends
from manager_terminator.autogenerated_graphql_client import GraphQLClient

from .depends import Settings
from .events import events_router

amqp_router = MORouter()
fastapi_router = APIRouter()

logger = structlog.get_logger(__name__)


@fastapi_router.post("/initiate/terminator/", status_code=HTTP_200_OK)
async def initiate_terminator(
    mo: depends.GraphQLClient, settings: Settings, dryrun: bool = False
):
    """
    This function serves as an initiator to be run first upon initiating the main
    application - the listener.
    When this functions endpoint has been called, any current manager roles
    without an active engagement or a person attached to the role, will be terminated.

    Args:
        mo: A MO client used to perform various queries and mutations in MO.
    """

    manager_objects = await managers.get(mo)
    manager_invalid_periods = managers.invalid_manager_periods(manager_objects)
    if len(manager_invalid_periods) < 1:
        logger.info("No invalid manager periods found.")
        return

    logger.info(
        "Found invalid manager periods:",
        manager_invalid_periods=json.dumps(jsonable_encoder(manager_invalid_periods)),
    )

    if dryrun:
        return

    if settings.manager_terminator.set_to_vacant:
        updated_invalid_manager_periods = await managers.update_manager_to_vacant(
            mo, manager_invalid_periods
        )

        logger.info(
            "Updated invalid periods for manager(s) to vacant: %s"
            % json.dumps(jsonable_encoder(updated_invalid_manager_periods))
        )
    else:
        terminated_invalid_manager_periods = await managers.terminate_manager_periods(
            mo, manager_invalid_periods
        )

        logger.info(
            "Terminated invalid periods for manager(s): %s"
            % json.dumps(jsonable_encoder(terminated_invalid_manager_periods))
        )


def create_app() -> FastAPI:
    settings = Settings()
    fastramqpi = FastRAMQPI(
        application_name="os2mo-manager-terminator",
        settings=settings.fastramqpi,
        graphql_version=29,
        graphql_client_cls=GraphQLClient,
        graphql_events=GraphQLEvents(
            declare_listeners=[
                Listener(
                    namespace="mo",
                    user_key="engagement",
                    routing_key="engagement",
                    path="/events/engagement",
                )
            ]
        ),
    )

    fastramqpi.add_context(settings=settings)

    app = fastramqpi.get_app()
    app.include_router(events_router)

    return app
