# SPDX-FileCopyrightText: 2023 Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0

import structlog
from fastapi import FastAPI
from fastramqpi.events import GraphQLEvents
from fastramqpi.events import Listener
from fastramqpi.events import Namespace
from fastramqpi.main import FastRAMQPI

from manager_terminator.autogenerated_graphql_client import GraphQLClient

from .depends import Settings
from .events import events_router

logger = structlog.get_logger(__name__)


def create_app() -> FastAPI:
    settings = Settings()

    listeners = []
    if settings.listen_to_changes_in_mo:
        listeners = [
            # listeners for mo events
            Listener(
                namespace="mo",
                user_key="engagement",
                routing_key="engagement",
                path="/events/engagement",
            ),
            Listener(
                namespace="mo",
                user_key="manager",
                routing_key="manager",
                path="/events/mo/manager",
            ),
            # listeners for internal events
            Listener(
                namespace="manager-terminator",
                user_key="manager",
                routing_key="manager",
                path="/events/manager-terminator/manager",
            ),
        ]

    fastramqpi = FastRAMQPI(
        application_name="os2mo-manager-terminator",
        settings=settings.fastramqpi,
        graphql_version=29,
        graphql_client_cls=GraphQLClient,
        graphql_events=GraphQLEvents(
            declare_listeners=listeners,
            declare_namespaces=[Namespace(name="manager-terminator")],
        ),
    )

    fastramqpi.add_context(settings=settings)

    app = fastramqpi.get_app()
    app.include_router(events_router)

    return app
