# SPDX-FileCopyrightText: 2023 Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
import json
from collections.abc import Generator
from datetime import datetime
from typing import Any
from uuid import UUID

import structlog
from fastapi.encoders import jsonable_encoder

from manager_terminator.autogenerated_graphql_client import EmployeeFilter
from manager_terminator.autogenerated_graphql_client import ManagerFilter
from manager_terminator.autogenerated_graphql_client import (
    TerminateManagerManagerTerminate,
)
from manager_terminator.autogenerated_graphql_client import UpdateManagerManagerUpdate
from manager_terminator.autogenerated_graphql_client.client import GraphQLClient
from manager_terminator.autogenerated_graphql_client.get_managers import (
    GetManagersManagersObjects,
)
from manager_terminator.autogenerated_graphql_client.get_managers import (
    GetManagersManagersObjectsValidities,
)
from manager_terminator.autogenerated_graphql_client.get_managers import (
    GetManagersManagersObjectsValiditiesPersonEngagementsValidity,
)
from manager_terminator.models import InvalidManagerPeriod
from manager_terminator.models import ManagerState
from manager_terminator.utils import POSITIVE_INFINITY

logger = structlog.get_logger(__name__)


async def get(mo: GraphQLClient) -> list[GetManagersManagersObjects]:
    """Fetches all manager objects from MO using GraphQL.

    Note: The GraphQL query fetches "objects" and not "current", since we want to examine
    all manager objects, even if they are not currently active.
    """

    gql_response = await mo.get_managers(ManagerFilter(from_date=None, to_date=None))
    return gql_response.objects


async def get_by_employee_uuids(
    mo: GraphQLClient, employee_uuids: list[UUID]
) -> list[GetManagersManagersObjects]:
    gql_response = await mo.get_managers(
        ManagerFilter(
            employee=EmployeeFilter(
                uuids=employee_uuids,
            ),
            from_date=None,
            to_date=None,
        )
    )
    return gql_response.objects


async def invalid_manager_periods(
    managers: list[GetManagersManagersObjects],
) -> list[InvalidManagerPeriod]:
    """Goes through a list of managers and returns periods, if any, where the manager is invalid.

    An invalid manager period, is a period where the manager validity is ACTIVE,
    but the related manager-employee does not have an ACTIVE engagement in *any* org_unit
    in the same period.

    ```
    Initial:
                ===================================================
    -----   ----------                ------------------         --------           ------------
                -----------
    Invalid periods:

                            |INVALID|                  |INVALID|
                ============         ==================         ===
    -----   ----------               ------------------         --------           ------------
                 -----------
    ```
    """
    all_invalid_periods = []
    for manager in managers:
        for manager_obj in manager.validities:
            valid_engagement_validities = [
                engagement.validity
                for manager_employee in manager_obj.person or []
                for engagement in manager_employee.engagements or []
            ]

            all_invalid_periods.extend(
                _find_gaps(manager_obj, valid_engagement_validities)
            )

    return all_invalid_periods


async def terminate_manager_periods(
    mo: GraphQLClient, periods: list[InvalidManagerPeriod]
) -> list[TerminateManagerManagerTerminate]:
    terminated_manager_periods = []
    for period in periods:
        terminate_args: dict[str, Any] = {
            "uuid": period.uuid,
            "terminate_from": period.from_.date(),
            "terminate_to": period.to.date(),
        }
        if period.to is POSITIVE_INFINITY:
            terminate_args["terminate_from"] = None
            terminate_args["terminate_to"] = period.from_.date()

        try:
            terminated_manager_periods.append(
                await mo.terminate_manager(**terminate_args)
            )
        except Exception as e:
            logger.error(
                "Failed to terminate invalid manager period: %s"
                % json.dumps(jsonable_encoder(period))
            )
            raise e

    return terminated_manager_periods


async def update_manager_to_vacant(
    mo: GraphQLClient, periods: list[InvalidManagerPeriod]
) -> list[UpdateManagerManagerUpdate]:
    updated_manager_periods = []
    for period in periods:
        update_args: dict[str, Any] = {
            "uuid": period.uuid,
            "vacant_from": period.from_.date(),
            "vacant_to": period.to.date(),
        }

        if period.to is POSITIVE_INFINITY:
            update_args["vacant_to"] = None
            update_args["vacant_from"] = period.from_.date()

        try:
            updated_manager_periods.append(await mo.update_manager(**update_args))
        except Exception as e:
            logger.error(
                "Failed to update invalid manager period to vacant: %s"
                % json.dumps(jsonable_encoder(period))
            )
            raise e

    return updated_manager_periods


# Helper methods for this module


def _find_gaps(
    manager: GetManagersManagersObjectsValidities,
    engagement_validities: list[
        GetManagersManagersObjectsValiditiesPersonEngagementsValidity
    ],
) -> Generator[InvalidManagerPeriod]:
    manager_validity_to = manager.validity.to or POSITIVE_INFINITY
    manager_endpoints = {manager.validity.from_, manager_validity_to}
    engagement_endpoints = {
        date
        for validity in engagement_validities
        for date in (validity.from_, validity.to or POSITIVE_INFINITY)
    }
    endpoints = sorted(manager_endpoints.union(engagement_endpoints))

    # track "invalid manager periods", i.e. periods where a manager
    # is SET but has no associated engagement. Yields each such period on exit.
    invalid_period_start: datetime | None = None
    for endpoint in endpoints:
        manager_state: ManagerState = _manager_state_at(manager, endpoint)
        engagement_exists: bool = _engagement_exists_at(engagement_validities, endpoint)

        if invalid_period_start is not None:
            # inside an invalid period, check if it has ended
            manager_no_longer_set = manager_state in (
                ManagerState.NOT_SET,
                ManagerState.VACANT,
            )
            should_end_invalid_period = engagement_exists or manager_no_longer_set

            if should_end_invalid_period:
                yield InvalidManagerPeriod(
                    uuid=manager.uuid, from_=invalid_period_start, to=endpoint
                )
                invalid_period_start = None

        else:
            # outside an invalid period, check if one has started
            if manager_state == ManagerState.SET and not engagement_exists:
                invalid_period_start = endpoint

    # close any still-open invalid period (happens when manager is open-ended)
    if invalid_period_start is not None:
        yield InvalidManagerPeriod(
            uuid=manager.uuid, from_=invalid_period_start, to=manager_validity_to
        )


def _manager_state_at(
    manager: GetManagersManagersObjectsValidities, at: datetime
) -> ManagerState:
    """Returns whether the manager is set at the given point in time"""

    if at < manager.validity.from_:
        return ManagerState.NOT_SET

    if manager.validity.to and at >= manager.validity.to:
        # at is after manager validity
        return ManagerState.NOT_SET

    if manager.person is None:
        return ManagerState.VACANT

    return ManagerState.SET


def _engagement_exists_at(
    engagement_validities: list[
        GetManagersManagersObjectsValiditiesPersonEngagementsValidity
    ],
    at: datetime,
) -> bool:
    """Returns whether there is an engagements at the given point in time"""
    return any(
        validity.from_ <= at < (validity.to or POSITIVE_INFINITY)
        for validity in engagement_validities
    )
