# SPDX-FileCopyrightText: 2023 Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
import json
from itertools import pairwise
from typing import Any
from uuid import UUID

import structlog
from fastapi.encoders import jsonable_encoder

from manager_terminator.autogenerated_graphql_client import EmployeeFilter
from manager_terminator.autogenerated_graphql_client import ManagerFilter
from manager_terminator.autogenerated_graphql_client import (
    TerminateManagerManagerTerminate,
)
from manager_terminator.autogenerated_graphql_client import UpdateManagerManagerUpdate
from manager_terminator.autogenerated_graphql_client.client import GraphQLClient
from manager_terminator.autogenerated_graphql_client.get_managers import (
    GetManagersManagersObjects,
)
from manager_terminator.exceptions import NoValueError
from manager_terminator.models import Active
from manager_terminator.models import InvalidManagerPeriod
from manager_terminator.models import Manager
from manager_terminator.models import ManagerStatus
from manager_terminator.models import ManagerValue
from manager_terminator.models import Timeline
from manager_terminator.models import combine_intervals
from manager_terminator.models import merge_overlapping_intervals
from manager_terminator.utils import POSITIVE_INFINITY

logger = structlog.get_logger(__name__)


async def get(mo: GraphQLClient) -> list[GetManagersManagersObjects]:
    """Fetches all manager objects from MO using GraphQL.

    Note: The GraphQL query fetches "objects" and not "current", since we want to examine
    all manager objects, even if they are not currently active.
    """

    gql_response = await mo.get_managers(ManagerFilter(from_date=None, to_date=None))
    return gql_response.objects


async def get_by_employee_uuids(
    mo: GraphQLClient, employee_uuids: list[UUID]
) -> list[GetManagersManagersObjects]:
    gql_response = await mo.get_managers(
        ManagerFilter(
            employee=EmployeeFilter(
                uuids=employee_uuids,
            ),
            from_date=None,
            to_date=None,
        )
    )
    return gql_response.objects


def invalid_manager_periods(
    managers: list[GetManagersManagersObjects],
) -> list[InvalidManagerPeriod]:
    """Returns periods where the given managers are invalid.

    An invalid manager period is a period where a manager validity is ACTIVE,
    but the related manager-employee does not have any active engagement. The
    rationale being that a person needs to be employed in order to be a manager.

    # Example

    Assume a person has two manager roles and two engagements:
    ```
    manager1             |-----------------------------------|
    manager2                                           |-----------------|
    engagement1                |-----------|
    engagement2                      |-----------|     |-----------|
    ---
    manager1 is invalid  |=====|                 |=====|
    manager2 is invalid                                            |=====|
    ```
    """
    logger.warn("got managers", managers=managers)

    return [
        period
        for manager in managers
        for period in _find_invalid_periods_for_one_manager(manager)
    ]


def _find_invalid_periods_for_one_manager(manager: GetManagersManagersObjects):
    manager_timeline = _make_manager_timeline(manager)
    engagement_timeline = _make_engagement_timeline(manager)
    endpoints = sorted(
        manager_timeline.get_interval_endpoints().union(
            engagement_timeline.get_interval_endpoints()
        )
    )
    for start, end in pairwise(endpoints):
        try:
            manager_value = manager_timeline.entity_at(start).value
        except NoValueError:
            manager_value = None

        engagement_active: bool
        try:
            engagement_active = engagement_timeline.entity_at(start).value  # type: ignore[assignment]  # mypy doesn't understand generics
        except NoValueError:
            engagement_active = False  # type: ignore[assignment]  # mypy doesn't understand generics

        match (manager_value, engagement_active):
            case (ManagerValue(status=ManagerStatus.ACTIVE, uuid=uuid), False):
                yield InvalidManagerPeriod(uuid=uuid, from_=start, to=end)


def _make_manager_timeline(manager: GetManagersManagersObjects) -> Timeline[Manager]:
    manager_intervals = (
        Manager(
            start=manager_obj.validity.from_,
            end=manager_obj.validity.to or POSITIVE_INFINITY,
            value=ManagerValue(
                uuid=manager_obj.uuid,
                status=ManagerStatus.ACTIVE
                if manager_obj.person
                else ManagerStatus.VACANT,
            ),
        )
        for manager_obj in manager.validities
    )
    manager_intervals_sorted = tuple(
        sorted(manager_intervals, key=lambda manager: manager.start)
    )
    manager_intervals_combined = combine_intervals(manager_intervals_sorted)
    return Timeline(intervals=manager_intervals_combined)


def _make_engagement_timeline(
    manager: GetManagersManagersObjects,
) -> Timeline[Active]:
    engagement_intervals = (
        Active(
            start=engagement.validity.from_,
            end=engagement.validity.to or POSITIVE_INFINITY,
            value=True,
        )
        for manager_obj in manager.validities
        for manager_employee in (manager_obj.person or [])
        for engagement in (manager_employee.engagements or [])
    )
    engagement_intervals_sorted = tuple(
        sorted(engagement_intervals, key=lambda manager: manager.start)
    )
    engagement_intervals_merged = merge_overlapping_intervals(
        engagement_intervals_sorted
    )
    return Timeline(intervals=engagement_intervals_merged)


async def terminate_manager_periods(
    mo: GraphQLClient, periods: list[InvalidManagerPeriod]
) -> list[TerminateManagerManagerTerminate]:
    terminated_manager_periods = []
    for period in periods:
        terminate_args: dict[str, Any] = {
            "uuid": period.uuid,
            "terminate_from": period.from_.date(),
            "terminate_to": period.to.date(),
        }
        if period.to is POSITIVE_INFINITY:
            terminate_args["terminate_from"] = None
            terminate_args["terminate_to"] = period.from_.date()
        try:
            terminated_manager_periods.append(
                await mo.terminate_manager(**terminate_args)
            )
        except Exception as e:  # pragma: no cover
            logger.error(
                "Failed to terminate invalid manager period: %s"
                % json.dumps(jsonable_encoder(period))
            )
            raise e

    return terminated_manager_periods


async def update_manager_to_vacant(
    mo: GraphQLClient, periods: list[InvalidManagerPeriod]
) -> list[UpdateManagerManagerUpdate]:
    updated_manager_periods = []
    for period in periods:
        update_args: dict[str, Any] = {
            "uuid": period.uuid,
            "vacant_from": period.from_.date(),
            "vacant_to": period.to.date(),
        }

        if period.to is POSITIVE_INFINITY:
            update_args["vacant_to"] = None
            update_args["vacant_from"] = period.from_.date()

        try:
            updated_manager_periods.append(await mo.update_manager(**update_args))
        except Exception as e:  # pragma: no cover
            logger.error(
                "Failed to update invalid manager period to vacant: %s"
                % json.dumps(jsonable_encoder(period))
            )
            raise e

    return updated_manager_periods
