# SPDX-FileCopyrightText: 2023 Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
import json
from typing import Any
from uuid import UUID

import structlog
from fastapi.encoders import jsonable_encoder

from manager_terminator.autogenerated_graphql_client import EmployeeFilter
from manager_terminator.autogenerated_graphql_client import ManagerFilter
from manager_terminator.autogenerated_graphql_client import (
    TerminateManagerManagerTerminate,
)
from manager_terminator.autogenerated_graphql_client import UpdateManagerManagerUpdate
from manager_terminator.autogenerated_graphql_client.client import GraphQLClient
from manager_terminator.autogenerated_graphql_client.get_managers import (
    GetManagersManagersObjects,
)
from manager_terminator.models import InvalidManagerPeriod
from manager_terminator.utils import POSITIVE_INFINITY

logger = structlog.get_logger(__name__)


async def get(mo: GraphQLClient) -> list[GetManagersManagersObjects]:
    """Fetches all manager objects from MO using GraphQL.

    Note: The GraphQL query fetches "objects" and not "current", since we want to examine
    all manager objects, even if they are not currently active.
    """

    gql_response = await mo.get_managers(ManagerFilter(from_date=None, to_date=None))
    return gql_response.objects


async def get_by_employee_uuids(
    mo: GraphQLClient, employee_uuids: list[UUID]
) -> list[GetManagersManagersObjects]:
    gql_response = await mo.get_managers(
        ManagerFilter(
            employee=EmployeeFilter(
                uuids=employee_uuids,
            ),
            from_date=None,
            to_date=None,
        )
    )
    return gql_response.objects


async def terminate_manager_periods(
    mo: GraphQLClient, periods: list[InvalidManagerPeriod]
) -> list[TerminateManagerManagerTerminate]:
    terminated_manager_periods = []
    for period in periods:
        terminate_args: dict[str, Any] = {
            "uuid": period.uuid,
            "terminate_from": period.from_.date(),
            "terminate_to": period.to.date(),
        }
        if period.to is POSITIVE_INFINITY:
            terminate_args["terminate_from"] = None
            terminate_args["terminate_to"] = period.from_.date()

        try:
            terminated_manager_periods.append(
                await mo.terminate_manager(**terminate_args)
            )
        except Exception as e:
            logger.error(
                "Failed to terminate invalid manager period: %s"
                % json.dumps(jsonable_encoder(period))
            )
            raise e

    return terminated_manager_periods


async def update_manager_to_vacant(
    mo: GraphQLClient, periods: list[InvalidManagerPeriod]
) -> list[UpdateManagerManagerUpdate]:
    updated_manager_periods = []
    for period in periods:
        update_args: dict[str, Any] = {
            "uuid": period.uuid,
            "vacant_from": period.from_.date(),
            "vacant_to": period.to.date(),
        }

        if period.to is POSITIVE_INFINITY:
            update_args["vacant_to"] = None
            update_args["vacant_from"] = period.from_.date()

        try:
            updated_manager_periods.append(await mo.update_manager(**update_args))
        except Exception as e:
            logger.error(
                "Failed to update invalid manager period to vacant: %s"
                % json.dumps(jsonable_encoder(period))
            )
            raise e

    return updated_manager_periods
