# SPDX-FileCopyrightText: 2023 Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
import datetime
from zoneinfo import ZoneInfo

from manager_terminator.autogenerated_graphql_client.get_managers import (
    GetManagersManagersObjectsObjectsEmployeeEngagementsValidity,
)
from manager_terminator.autogenerated_graphql_client.get_managers import (
    GetManagersManagersObjectsObjectsValidity,
)


DEFAULT_TIMEZONE = ZoneInfo("Europe/Copenhagen")
POSITIVE_INFINITY = datetime.datetime.max.replace(tzinfo=datetime.UTC)


def validity_timezone_aware(
    validity: GetManagersManagersObjectsObjectsValidity
    | GetManagersManagersObjectsObjectsEmployeeEngagementsValidity,
):
    return {
        "from": validity.from_.replace(tzinfo=DEFAULT_TIMEZONE),
        "to": validity.to.replace(tzinfo=DEFAULT_TIMEZONE) if validity.to else None,
    }
